# Generated by Django 5.0.6 on 2024-06-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.IntegerField(choices=[('available', 1), ('not available', 0)], default=1),
        ),
    ]
