# Generated by Django 5.0.6 on 2024-06-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_book_borrow_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_borrow',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='book_borrow',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_borrow',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
