# Generated by Django 5.0.6 on 2024-06-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_remove_book_borrow_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_borrow',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
