# Generated by Django 5.0.6 on 2024-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_alter_book_borrow_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_borrow',
            name='is_confirmed',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
