# Generated by Django 5.0.6 on 2024-06-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_alter_book_borrow_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_borrow',
            old_name='is_confirmed',
            new_name='status',
        ),
        migrations.AddField(
            model_name='book_borrow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book_borrow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_borrow',
            name='borrow_date',
            field=models.DateTimeField(null=True),
        ),
    ]
