# Generated by Django 5.0.6 on 2024-06-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0007_alter_book_borrow_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_borrow',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='book_borrow',
            old_name='user_id',
            new_name='user',
        ),
    ]
